# docker-compose.yaml
version: '3.8'

services:
  mysql:
    image: mysql:latest
    env_file:
      - .env
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  adminer:
    image: adminer:latest
    ports:
      - "${ADMINER_PORT}:8080"

  fastapi:
    build:
      context: ./fastapi
    ports:
      - "${FASTAPI_PORT}:8000"
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

volumes:
  mysql_data:

